version: '3.1'

services:
  postgres:
    image: postgres
    volumes:
      - ./pgdb/:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_NAME=Django
      - POSTGRES_USER=Test
      - POSTGRES_PASSWORD=12345
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

